<?php

/**
 * Licentia Pictura - Banner Management
 *
 * NOTICE OF LICENSE
 * This source file is subject to the European Union Public Licence
 * It is available through the world-wide-web at this URL:
 * http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 *
 * @title      Background Management
 * @category   Marketing
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) 2014 Licentia - http://licentia.pt
 * @license    European Union Public Licence
 */
class Licentia_Pictura_Block_Adminhtml_Banners_Edit_Tab_Main extends Mage_Adminhtml_Block_Widget_Form {

    protected function _prepareForm() {
        $current = Mage::registry("current_banner");

        $form = new Varien_Data_Form();
        $this->setForm($form);
        $fieldset = $form->addFieldset("pictura_form", array("legend" => $this->__("Banners Information")));

        $fieldset->addField("name", "text", array(
            "label" => $this->__("Name"),
            "class" => "required-entry",
            "required" => true,
            "name" => "name",
        ));

        $param = Mage::getStoreConfig('pictura/config/param');

        $fieldset->addField("code", "text", array(
            "label" => $this->__("Tracking Code"),
            "name" => "code",
            "note" => "Leave Empty for autogenerated. Use this code to track banner conversions. Ex: " . Mage::getStoreConfig('web/secure/base_url') . "?{$param}=THIS_CODE",
        ));

        $fieldset->addField("is_active", "select", array(
            "label" => $this->__("Is Active"),
            "options" => array('1' => $this->__('Yes'), '0' => $this->__('No')),
            "name" => "is_active",
        ));

        $outputFormatDate = Mage::app()->getLocale()->getDateFormat(Mage_Core_Model_Locale::FORMAT_TYPE_SHORT);
        $fieldset->addField('date_start', 'date', array(
            'name' => 'date_start',
            'format' => $outputFormatDate,
            'label' => $this->__('Active From Date'),
            'image' => $this->getSkinUrl('images/grid-cal.gif'),
        ));

        $fieldset->addField('date_end', 'date', array(
            'name' => 'date_end',
            'format' => $outputFormatDate,
            'label' => $this->__('Active To Date'),
            'image' => $this->getSkinUrl('images/grid-cal.gif'),
        ));

        $fieldset->addField("positions", "multiselect", array(
            "label" => $this->__("Banner Positions"),
            "name" => "positions",
            "required" => true,
            "type" => "options",
            "values" => Mage::getModel('pictura/banners')->getBannerTypes('All'),
        ));
        $form->getElement('positions')->setData('size', 6);

        if (Mage::helper('pictura')->magna()) {
            $values = Mage::getModel('magna/segments')->getOptionArray('All');

            $fieldset->addField("segments", "multiselect", array(
                "label" => $this->__("Customer Segments"),
                "required" => true,
                "name" => "segments",
                "type" => "options",
                "values" => $values,
            ));
            $form->getElement('segments')->setData('size', count($values) > 10 ? 10 : count($values));
        }

        if (!$current->getId()) {
            $form->addValues(array('segments' => array('0'), 'positions' => array('0')));
        }

        if ($current) {
            $currentValues = $current->getData();
            $form->addValues($currentValues);
        }
        if (count($current->getData('positions')) == 0) {
            $form->addValues(array('positions' => array('0')));
        }

        if (count($current->getData('segments')) == 0) {
            $form->addValues(array('segments' => array('0')));
        }

        return parent::_prepareForm();
    }

}
